[package]
name = "logwatch"
version = "0.1.0"
authors = ["Kongou <kongou@shipfu.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"

[dev-dependencies]
rand = "0.7.3"